1. Basic Python Machine Learning Packages(AP24110011603)

The PDF introduces four important packages:

NumPy
Pandas
Matplotlib
SciPy

Pandas, NumPy and Matplotlib are commonly used for data analysis, while SciPy provides additional scientific and engineering functions.

NumPy

NumPy stands for Numerical Python.

It is mainly used for:

Arrays
Mathematical calculations
Numerical operations
Linear algebra

Example:

import numpy as np

Here np is the short name/alias used for NumPy.

Pandas

Pandas provides high-level data structures for working with structured/tabular data. Its two major data structures are:

Series → one-dimensional
DataFrame → two-dimensional

Matplotlib

Matplotlib is used to create:

Graphs
Charts
Plots
2D visualizations

It is especially useful for visualizing data.

SciPy

SciPy provides scientific and engineering functions.

2. Scikit-learn (AP24110011603)

The PDF also introduces scikit-learn, a general-purpose machine-learning toolkit for Python.

It supports:

Classification

Used when the output belongs to categories.

Examples:

SVM
Nearest Neighbors
Random Forest
Logistic Regression
Regression

Used to predict numerical values.

Examples:

Lasso Regression
Ridge Regression
Clustering

Used to group similar data.

Examples:

K-Means
Spectral Clustering
Dimensionality Reduction

Used to reduce the number of features.

Examples:

PCA
Feature Selection
Matrix Factorization
Model Selection

Includes:

Grid Search
Cross-validation
Metrics
Preprocessing

Includes:

Feature extraction
Normalization

3). Pandas Data Structures

The PDF says Pandas mainly provides two data structures:

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)
import numpy as np               # Import NumPy library

info = np.array(['S','I','V','A'])  # Create a NumPy array containing S, I, V and A

a = pd.Series(info)              # Convert the NumPy array into a Pandas Series

print(a)                         # Display the Series

0    S
1    I
2    V
3    A
dtype: object

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)

df = pd.DataFrame()               # Create an empty DataFrame

print(df)                         # Display the empty DataFrame

Empty DataFrame
Columns: []
Index: []

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)

x = ['Siva', 'Rama', 'Krishna']  # Create a list containing three names

df = pd.DataFrame(x)              # Convert the list into a DataFrame

print(df)                         # Display the DataFrame

         0
0     Siva
1     Rama
2  Krishna

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)

info = {                          # Create a dictionary
    'ID': [1001, 1002, 1003],    # Create ID column with three values
    'Department': ['B.Tech', 'M.Tech', 'PhD']  # Create Department column
}

df = pd.DataFrame(info)           # Convert the dictionary into a DataFrame

print(df)                         # Display the DataFrame

     ID Department
0  1001     B.Tech
1  1002     M.Tech
2  1003        PhD

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)

info = {                          # Create a dictionary
    'one': pd.Series(             # Create the first Series
        [1, 2, 3, 4, 5, 6],      # Values
        index=['a','b','c','d','e','f']  # Index labels
    ),

    'two': pd.Series(             # Create the second Series
        [1, 2, 3, 4, 5, 6, 7, 8], # Values
        index=['a','b','c','d','e','f','g','h'] # Index labels
    )
}

d1 = pd.DataFrame(info)           # Create DataFrame from the dictionary

print(d1)                         # Display the complete DataFrame

print(d1['one'])                  # Select and display the 'one' column

print(d1['two'])                  # Select and display the 'two' column

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    NaN
h    NaN
Name: one, dtype: float64
a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
Name: two, dtype: int64

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)

info = {                          # Create a dictionary
    'one': pd.Series(             # Create column 'one'
        [1, 2, 3, 4, 5],         # Values for column one
        index=['a','b','c','d','e'] # Index labels
    ),

    'two': pd.Series(             # Create column 'two'
        [1, 2, 3, 4, 5, 6],      # Values for column two
        index=['a','b','c','d','e','f'] # Index labels
    )
}

df = pd.DataFrame(info)           # Create DataFrame

print(df)                         # Display the original DataFrame

print("Add new column by passing series")  # Display a message

df['three'] = pd.Series(           # Create a new column named 'three'
    [20, 40, 60],                 # Values for the new column
    index=['a','b','c']            # Index labels for the new values
)

print(df)                         # Display DataFrame after adding column three

print("Add new column using existing DataFrame columns")  # Display a message

df['four'] = df['one'] + df['three']  # Add columns one and three and store result in four

print(df)                         # Display the final DataFrame

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
Add new column by passing series
   one  two  three
a  1.0    1   20.0
b  2.0    2   40.0
c  3.0    3   60.0
d  4.0    4    NaN
e  5.0    5    NaN
f  NaN    6    NaN
Add new column using existing DataFrame columns
   one  two  three  four
a  1.0    1   20.0  21.0
b  2.0    2   40.0  42.0
c  3.0    3   60.0  63.0
d  4.0    4    NaN   NaN
e  5.0    5    NaN   NaN
f  NaN    6    NaN   NaN

In [ ]:
import pandas as pd              # Import Pandas library(AP24110011603)

info = {                          # Create a dictionary
    'one': pd.Series(             # Create column one
        [1, 2],                   # Values
        index=['a','b']            # Index labels
    ),

    'two': pd.Series(             # Create column two
        [1, 2, 3],                # Values
        index=['a','b','c']        # Index labels
    )
}

df = pd.DataFrame(info)           # Create DataFrame from dictionary

print("The DataFrame:")            # Display a message

print(df)                         # Display the DataFrame

print("Delete the first column:")  # Display a deletion message

del df['one']                     # Delete column 'one' using del

print(df)                         # Display DataFrame after deletion

print("Delete the another column:") # Display another deletion message

df.pop('two')                     # Remove column 'two' using pop()

print(df)                         # Display the final DataFrame

The DataFrame:
   one  two
a  1.0    1
b  2.0    2
c  NaN    3
Delete the first column:
   two
a    1
b    2
c    3
Delete the another column:
Empty DataFrame
Columns: []
Index: [a, b, c]

In [ ]:
import pandas as pd              # Import Pandas library

info = {                          # Create a dictionary(AP24110011603)
    'one': pd.Series(             # Create column one
        [1, 2, 3, 4, 5],         # Values
        index=['a','b','c','d','e'] # Index labels
    ),

    'two': pd.Series(             # Create column two
        [1, 2, 3, 4, 5, 6],      # Values
        index=['a','b','c','d','e','f'] # Index labels
    )
}

df = pd.DataFrame(info)           # Create DataFrame

print("Data frame:")              # Display a message

print(df)                         # Display the DataFrame

print("b index elements are:")    # Display message for row b

print(df.loc['b'])                # Select row with label 'b'

print("e index elements are:")    # Display message for row e

print(df.loc['e'])                # Select row with label 'e'

Data frame:
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
b index elements are:
one    2.0
two    2.0
Name: b, dtype: float64
e index elements are:
one    5.0
two    5.0
Name: e, dtype: float64

In [ ]:
import pandas as pd              # Import Pandas library

info = {                          # Create a dictionary
    'one': pd.Series(             # Create column one
        [1, 2, 3, 4, 5],         # Values
        index=['a','b','c','d','e'] # Index labels
    ),

    'two': pd.Series(             # Create column two
        [1, 2, 3, 4, 5, 6],      # Values(AP24110011603)
        index=['a','b','c','d','e','f'] # Index labels
    )
}

df = pd.DataFrame(info)           # Create DataFrame

print(df)                         # Display DataFrame

print(df.iloc[3])                 # Select the fourth row using integer position

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
one    4.0
two    4.0
Name: d, dtype: float64

In [ ]:
df.iloc[3]                        # Select row at position 3

one    4.0
two    4.0
Name: d, dtype: float64

0 = First row
1 = Second row
2 = Third row
3 = Fourth row

iloc = integer-location based selection

In [ ]:
import pandas as pd              # Import Pandas library

info = {                          # Create a dictionary
    'one': pd.Series(             # Create column one
        [1, 2, 3, 4, 5],         # Values(AP24110011603)
        index=['a','b','c','d','e'] # Index labels
    ),

    'two': pd.Series(             # Create column two
        [1, 2, 3, 4, 5, 6],      # Values
        index=['a','b','c','d','e','f'] # Index labels
    )
}

df = pd.DataFrame(info)           # Create DataFrame

print(df)                         # Display DataFrame

print(df[2:5])                    # Select rows from position 2 up to, but not including, 5

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
   one  two
c  3.0    3
d  4.0    4
e  5.0    5

### Filtering Rows by Column Value

You can filter rows based on conditions applied to specific columns. This is often done using boolean indexing.

In [ ]:
# Create a sample DataFrame for demonstration(AP24110011603)
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'London', 'Paris', 'New York']}
sample_df = pd.DataFrame(data)

print("Original DataFrame:")
display(sample_df)

Original DataFrame:

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   28  New York

In [ ]:
# Filter rows where 'Age' is greater than 30
filtered_by_age = sample_df[sample_df['Age'] > 30]

print("Filtered by Age > 30:")
display(filtered_by_age)

Filtered by Age > 30:

      Name  Age   City
2  Charlie   35  Paris

In [ ]:
# Filter rows where 'City' is 'New York'
filtered_by_city = sample_df[sample_df['City'] == 'New York']

print("Filtered by City == 'New York':")
display(filtered_by_city)

Filtered by City == 'New York':

    Name  Age      City
0  Alice   25  New York
3  David   28  New York

In [ ]:
# Filter rows with multiple conditions (Age > 25 and City is 'New York')(AP24110011603)
filtered_by_multiple_conditions = sample_df[(sample_df['Age'] > 25) & (sample_df['City'] == 'New York')]

print("Filtered by Age > 25 AND City == 'New York':")
display(filtered_by_multiple_conditions)

Filtered by Age > 25 AND City == 'New York':

    Name  Age      City
3  David   28  New York

So 2:5 selects:

Position 2
Position 3
Position 4

In [ ]:
import pandas as pd              # Import Pandas library

d = pd.DataFrame({                # Create the first DataFrame
    'A': [1, 2, 3],              # Create column A
    'B': [4, 5, 6]               # Create column B
})

d2 = pd.DataFrame({               # Create the second DataFrame
    'A': [7, 8, 9],              # Create column A
    'B': [10, 11, 12]            # Create column B
})

d = pd.concat([d, d2])            # Combine the two DataFrames row-wise

print(d)                         # Display the combined DataFrame

   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

In [ ]:
pd.concat([d, d2])                # Combines DataFrames

   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12
0  7  10
1  8  11
2  9  12

In [ ]:
import pandas as pd              # Import Pandas library

a_info = pd.DataFrame(            # Create the first DataFrame
    [[4, 5], [6, 7]],             # Provide row values
    columns=['x', 'y']            # Give column names
)

b_info = pd.DataFrame(            # Create the second DataFrame
    [[8, 9], [10, 11]],           # Provide row values
    columns=['x', 'y']            # Give column names
)

a_info = pd.concat([a_info, b_info])  # Combine both DataFrames

print(a_info)                     # Display combined DataFrame

a_info = a_info.drop(0)           # Delete rows having index label 0

print(a_info)                     # Display DataFrame after deleting rows

    x   y
0   4   5
1   6   7
0   8   9
1  10  11
    x   y
1   6   7
1  10  11

If the same index occurs multiple times, all rows with that label can be removed.

In [ ]:
import pandas as pd              # Import Pandas library

data = {                          # Create a dictionary
    'Gender': ['F', 'M', 'M'],   # Create Gender column
    'Emp_ID': ['E01', 'E02', 'E03'], # Create employee ID column
    'Age': [25, 27, 25]           # Create Age column
}

df = pd.DataFrame(                # Create DataFrame
    data,                          # Pass dictionary as data
    columns=['Emp_ID', 'Gender', 'Age'] # Specify column order
)

print(df)                         # Display complete DataFrame

print(df.Emp_ID)                  # Display complete Emp_ID column

print(df.Emp_ID[0])               # Display first value of Emp_ID column

  Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25
0    E01
1    E02
2    E03
Name: Emp_ID, dtype: object
E01

In [ ]:
from google.colab import files

# This will open a file selection dialog in your browser
# After selecting the file, it will be uploaded to the Colab session
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving iris.csv to iris.csv
User uploaded file "iris.csv" with length 3858 bytes

In [ ]:
import pandas as pd              # Import Pandas library

emp = {                            # Create a dictionary
    "Name": ["Siva", "Rama", "Krishna", "Siva"], # Create Name column
    "Age": [21, 32, 29, 21]       # Create Age column(AP24110011603)
}

info = pd.DataFrame(emp)           # Convert dictionary into DataFrame

print(info)                        # Display DataFrame before removing duplicates

info = info.drop_duplicates()      # Remove duplicate rows

print("After removing the duplicates the dataframe is :")  # Display message

print(info)                        # Display DataFrame after removing duplicates

      Name  Age
0     Siva   21
1     Rama   32
2  Krishna   29
3     Siva   21
After removing the duplicates the dataframe is :
      Name  Age
0     Siva   21
1     Rama   32
2  Krishna   29

In [ ]:
import pandas as pd              # Import Pandas library

import numpy as np               # Import NumPy library

info = pd.DataFrame({             # Create a DataFrame
    "Person": ["Siva", "Pavan", "Gopal", "Raghu"], # Create Person column
    "Age": [27., 29, np.nan, 32] # Create Age column; np.nan represents missing value
})

print(info)                       # Display the DataFrame

print(info.count())               # Count non-null values in each column

print("null values")              # Display a message

print(info.isnull())              # Check every cell for a null value

print(info.isnull().sum())        # Count total null values in each column

  Person   Age
0   Siva  27.0
1  Pavan  29.0
2  Gopal   NaN
3  Raghu  32.0
Person    4
Age       3
dtype: int64
null values
   Person    Age
0   False  False
1   False  False
2   False   True
3   False  False
Person    0
Age       1
dtype: int64

In [ ]:
import pandas as pd              # Import Pandas library

import numpy as np               # Import NumPy library

info = pd.DataFrame({             # Create a DataFrame
    "Person": ["Siva", "Pavan", "Gopal", "Raghu"], # Create Person column
    "Age": [27., 29, np.nan, 32] # Create Age column with one missing value
})

print(info)                       # Display original DataFrame

print("Sorting Order")            # Display sorting message

print(info.sort_index())          # Sort DataFrame by index in ascending order

print("Descending Order")         # Display descending-order message

print(info.sort_index(ascending=False)) # Sort DataFrame by index in descending order

  Person   Age
0   Siva  27.0
1  Pavan  29.0
2  Gopal   NaN
3  Raghu  32.0
Sorting Order
  Person   Age
0   Siva  27.0
1  Pavan  29.0
2  Gopal   NaN
3  Raghu  32.0
Descending Order
  Person   Age
3  Raghu  32.0
2  Gopal   NaN
1  Pavan  29.0
0   Siva  27.0

In [ ]:
import pandas as pd              # Import Pandas library

df = pd.read_csv('iris.csv')     # Read Iris dataset from CSV file

print(df)                        # Display the complete dataset(AP24110011603)

mean_df = df.groupby('species').mean()  # Group data by species and calculate mean

print("Mean values for each species:")  # Display a message

print(mean_df)                   # Display mean values for each species

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
Mean values for each species:
            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [ ]:
sum_df = df.groupby('species').sum()   # Group data by species and calculate sum

print("\nSum of values for each species:") # Display a message(AP24110011603)

print(sum_df)                           # Display sum values for each species

Sum of values for each species:
            sepal_length  sepal_width  petal_length  petal_width
species
setosa             250.3        171.4          73.1         12.3
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3